### ISSUE TITLE
'Add' button hidden by keyboard

### ISSUE THREAD

**Issue by harshad1** [felixwiemuth/SimpleReminder#17]
On my device, the 'add' button is hidden by the keyboard.

This makes adding a reminder _slightly_ harder, as I have to hide the keyboard first.

Please add the following information:
- App version: 0.9.7
- Android version: 11

My phone is a pixel 3 xl

**Comment by harshad1** [comment]
![Screenshot_20210606-110356](https://user-images.githubusercontent.com/1940940/120935637-9ae65300-c6b8-11eb-90d7-17448a35b073.png)

**Comment by felixwiemuth** [comment]
Hi @harshad1, the keyboard has a special action button on the bottom right which has the same effect as the "Add" button. Some keyboards will also display the label "Add", like the AOSP keyboard:

![Screenshot_20210607-113522](https://user-images.githubusercontent.com/533601/120995434-aeabbb00-c785-11eb-9275-d20567d65d25.png)

**Comment by felixwiemuth** [comment]
I assume that with the explanation this is solved. Should the "Add" button on the keyboard not work, this should of course be reported.
