### ISSUE TITLE
choosing a date in the future

### ISSUE THREAD

**Issue by OmlineEditor** [felixwiemuth/SimpleReminder#18]
I want to set a date in the future, I want a reminder in one week, but I can't do it because no date picker

**Comment by felixwiemuth** [comment]
See #10 .

**Comment by OmlineEditor** [comment]
make the date selection more convenient and understandable

**Comment by felixwiemuth** [comment]
Please read #10 - this feature does not exist yet, but will be added soon. :) You are welcome to comment on the way it is planned to be implemented.
