### ISSUE TITLE
Add A Quick Setting Tile

### ISSUE THREAD

**Issue by Tuweikan** [felixwiemuth/SimpleReminder#3]
Add a button in the notification panels so that its easier to just spawn the app and make the reminder notes immediately. Thanks!

**Comment by felixwiemuth** [comment]
Hi @imanincel, thanks for the suggestion. It sounds reasonable to have a Quick Setting tile "Add Reminder" that has the same effect as the launcher icon with the same name. For some this might be a bit faster or more convenient way to access the "Add Reminder" screen. I don't think it is necessary to have a Quick Setting tile for the reminders list screen.

**Comment by felixwiemuth** [comment]
This is now available in version 0.9.8, check it out!
