### ISSUE TITLE
part of the screen is not visible

### ISSUE THREAD

**Issue by OmlineEditor** [felixwiemuth/SimpleReminder#40]
part of the screen is not visible when entering a message, the OK button is hidden by a high keyboard. please change the window size and reduce it.

- App version: *0.9.11 F-Droid*
- Android version: *10*

![bug](https://github.com/felixwiemuth/SimpleReminder/assets/13348933/60a93d84-3d50-4bef-82d6-71f98a7a3e70)

**Comment by felixwiemuth** [comment]
This happens for small screens or high keyboards. However, if it's just the "Add" button that's hidden, one can use the "Ok" action from the keyboard to add the reminder. Even when the clock widget is partly covered it can actually still be used, including selecting positions which are hidden.
This is why I didn't see this as a high-priority issue.

It would be an option to make the size of the clock widget configurable and/or look for a more compact clock widget in general.

If anyone wants to contribute on this, let me know.

**Comment by OmlineEditor** [comment]
no, this is a problem, not all users understand that you can wait for the enter button. make the clock size dynamic or make a choice of how to show the clock as a round dial or just numbers.

**Comment by felixwiemuth** [comment]
This is now solved in version 0.9.13 (just released) via a setting where one can customize the size of the "Add reminder" screen in several ways.

This way, anyone who has problems with the clock or "Add" button being covered by the keyboard can make some parts of the UI smaller to avoid the issue, while others who prefer a larger clock can keep it this way (and use the clock and add reminders even when part of the UI is covered).

The implementation of #44 now also provides an additional way of dealing with hidden parts of the "Add reminder" screen: a new option allows to hide the keyboard when using the clock.

Everyone who had this issue, please test the new features and give feedback.
