### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by tuekacode** [felixwiemuth/SimpleReminder#5]
Dark amoled theme for the app :)

**Comment by felixwiemuth** [comment]
Certainly a nice-to-have, but I won't prioritize this right now as there are more important things to be added first. Luckily the part of the app one should see most is the "Add reminder" screen, and that is already dark. :)

**Comment by felixwiemuth** [comment]
I investigated this a bit further (see the [docs](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme) and this [Stackoverflow post](https://stackoverflow.com/questions/62938269/how-do-i-force-darken-the-webview-parent-so-that-i-can-use-websettingscompat-for)).

Android 10+ has a [Force Dark feature](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#force-dark) which (when enabled in the code) automatically generates a dark theme for a light-themed app. This seems to work quite well, only that the resulting colors for due and scheduled reminders are not so good. The WebViews for About/Help work quite well, except that they briefly show in white before turning dark (on my Android 12 device).

I think that for now this automatic dark theme is a good compromise, but eventually I would prefer a proper support for a dark theme (I will create a new issue).

**Comment by felixwiemuth** [comment]
Implemented in version 0.9.11.
