### ISSUE TITLE
Reminder App

### ISSUE THREAD

**Issue by Zodio25** [felixwiemuth/SimpleReminder#51]
i appreciate your work and I would like to see in the next update a reminder every hour (1 hour, 2 hours, 3 hours) it is for an elderly person who takes medication every 3 hours

**Comment by felixwiemuth** [comment]
Hi, thanks for your feedback.

Reminding schedules / recurring reminders are a planned feature, but it might take some time until it arrives, as there are some other important features in the queue.

Regarding your use case, please note that you must yourself evaluate the fitness of the app (in combination with your device) for this purpose and that there is no guarantee for reliability.

There are also other apps specifically for your use case.
